# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2EaKzn3GqgtpOAT72Q6cXJTST2kWd-v
"""

import streamlit as st
import datetime

# --- Page Configuration ---
st.set_page_config(page_title="BuildSmart CPMS", layout="wide")

# --- Initialize Session State (Database Memory) ---
# This ensures data isn't lost when interacting with the web page
if 'projects_db' not in st.session_state:
    st.session_state.projects_db = {}

# --- Header ---
st.title("🏗️ BuildSmart Construction Progress Monitoring")
st.markdown("Automated tracking system for construction schedule and cost variances.")
st.divider()

# --- Sidebar Navigation ---
st.sidebar.header("System Menu")
menu_choice = st.sidebar.radio(
    "Select Action:",
    ["1. Setup New Project", "2. Update Daily Progress", "3. Generate Progress Report"]
)

# --- Logic: Setup New Project ---
if menu_choice == "1. Setup New Project":
    st.header("Setup New Project & Activities")

    col1, col2 = st.columns(2)
    with col1:
        project_id = st.text_input("Project ID (e.g., P-01)").upper()
        project_name = st.text_input("Project Name")

    st.subheader("Add Activity")
    with st.form("activity_form"):
        act_id = st.text_input("Activity ID (e.g., ACT-01)").upper()
        act_name = st.text_input("Activity Name")
        col3, col4 = st.columns(2)
        with col3:
            planned_qty = st.number_input("Planned Quantity", min_value=0.0, step=1.0)
        with col4:
            budget = st.number_input("Allocated Budget (Rs.)", min_value=0.0, step=100.0)

        submit_btn = st.form_submit_button("Save Activity to System")

        if submit_btn:
            if project_id and project_name and act_id and act_name:
                # Initialize project if it doesn't exist
                if project_id not in st.session_state.projects_db:
                    st.session_state.projects_db[project_id] = {
                        "name": project_name,
                        "date": datetime.date.today().strftime("%Y-%m-%d"),
                        "activities": {}
                    }

                # Save activity data
                st.session_state.projects_db[project_id]["activities"][act_id] = {
                    "name": act_name,
                    "planned_qty": planned_qty,
                    "budget": budget,
                    "actual_qty": 0.0,
                    "actual_cost": 0.0
                }
                st.success(f"Activity '{act_name}' successfully added to {project_name}!")
            else:
                st.error("Error: Please fill in all text fields before saving.")

# --- Logic: Update Daily Progress ---
elif menu_choice == "2. Update Daily Progress":
    st.header("Update Daily Progress")

    if not st.session_state.projects_db:
        st.warning("No projects found. Please setup a project first.")
    else:
        project_list = list(st.session_state.projects_db.keys())
        selected_proj = st.selectbox("Select Project to Update", project_list)

        activities = st.session_state.projects_db[selected_proj]["activities"]
        if not activities:
            st.warning("No activities found in this project.")
        else:
            act_list = list(activities.keys())
            selected_act = st.selectbox("Select Activity", act_list)

            activity_data = activities[selected_act]
            st.info(f"Currently Updating: {activity_data['name']} | Planned Qty: {activity_data['planned_qty']}")

            with st.form("update_form"):
                qty_done = st.number_input("Quantity Completed Today", min_value=0.0)
                cost_incurred = st.number_input("Cost Incurred Today (Rs.)", min_value=0.0)

                update_btn = st.form_submit_button("Submit Progress Update")

                if update_btn:
                    # Update cumulative totals
                    st.session_state.projects_db[selected_proj]["activities"][selected_act]["actual_qty"] += qty_done
                    st.session_state.projects_db[selected_proj]["activities"][selected_act]["actual_cost"] += cost_incurred
                    st.success("Progress record successfully updated in the database!")

# --- Logic: Generate Progress Report ---
elif menu_choice == "3. Generate Progress Report":
    st.header("Project Progress Dashboard")

    if not st.session_state.projects_db:
        st.warning("No projects found. Please setup a project first.")
    else:
        project_list = list(st.session_state.projects_db.keys())
        selected_proj = st.selectbox("Select Project for Report", project_list)
        project_data = st.session_state.projects_db[selected_proj]

        st.subheader(f"Report: {project_data['name']} ({selected_proj})")

        total_budget = 0
        total_actual = 0

        for act_id, details in project_data["activities"].items():
            st.markdown(f"**Activity: {act_id} - {details['name']}**")

            planned_qty = details["planned_qty"]
            actual_qty = details["actual_qty"]
            budget = details["budget"]
            actual_cost = details["actual_cost"]

            total_budget += budget
            total_actual += actual_cost

            # Calculations
            percent_complete = (actual_qty / planned_qty * 100) if planned_qty > 0 else 0
            cost_variance = budget - actual_cost

            # Display Metrics
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Completion", f"{percent_complete:.1f}%")
            col2.metric("Actual Qty", f"{actual_qty} / {planned_qty}")
            col3.metric("Cost Variance", f"Rs. {cost_variance:,.2f}", delta=cost_variance)

            # Automated Alerts
            if cost_variance < 0:
                col4.error("BUDGET OVERRUN")
            elif percent_complete < 100 and percent_complete > 0:
                col4.warning("IN PROGRESS")
            elif percent_complete >= 100:
                col4.success("COMPLETED")
            else:
                col4.info("NOT STARTED")

            st.divider()

        st.markdown(f"### Total Project Budget: **Rs. {total_budget:,.2f}**")
        st.markdown(f"### Total Actual Cost: **Rs. {total_actual:,.2f}**")